<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <IsPackable>false</IsPackable>
    <!-- Avoid inheriting App RID when referencing App project. -->
    <RuntimeIdentifier></RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CareHR.UhfCardWriter.App\CareHR.UhfCardWriter.App.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\src\CareHR.UhfCardWriter.App\appsettings.json"
          Link="appsettings.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
